services:

  mysql:
    image: mysql:latest
    ports:
      - 127.0.0.1:43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2
    restart: no

  oracle:
    image: gvenzl/oracle-free:slim-faststart
    ports:
      - 127.0.0.1:41521:1521
      - 127.0.0.1:45500:5500
    environment:
      ORACLE_PASSWORD: "ddd53e85-b15e-4da8"
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_APEX: true
      ORACLE_DISABLE_JSON: true
      ORACLE_SGA_TARGET: 512
      ORACLE_PGA_AGGREGATE_TARGET: 256
    shm_size: '1gb'
    restart: no

  postgresql:
    image: pgvector/pgvector:pg18
    ports:
      - 127.0.0.1:45432:5432
    environment:
      POSTGRES_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2
    restart: no

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - 127.0.0.1:41433:1433
    environment:
      ACCEPT_EULA: true
      MSSQL_SA_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2
    restart: no
