using System.Data.Common;
using Oracle.ManagedDataAccess.Client;
using RepoDb.Oracle.IntegrationTests.Models;
using RepoDb.Schema;

namespace RepoDb.Oracle.IntegrationTests.Setup;

public static class Database
{
    private static readonly OracleDbInstance Instance = new();
    #region Properties

    /// <summary>
    /// Gets or sets the connection string to be used for SQL Server database.
    /// </summary>
    public static string ConnectionStringForMaster => Instance.AdminConnectionString;

    /// <summary>
    /// Gets or sets the connection string to be used.
    /// </summary>
    public static string ConnectionString => Instance.ConnectionString;

    #endregion

    #region Methods

    public static void Initialize()
    {
        GlobalConfiguration.Setup(new())
            .UseOracle();

        // Create tables
        CreateTables();
    }

    public static void Cleanup()
    {
        using var connection = new OracleConnection(ConnectionString);
        connection.Truncate<CompleteTable>();
        connection.Truncate<NonIdentityCompleteTable>();
        //connection.Truncate<MultiKeyTable>();
    }

    #endregion

    #region CreateTables

    private static void CreateTables()
    {
        using var connection = new OracleConnection(ConnectionString).EnsureOpen();
        CreateCompleteTable(connection);
        CreateNonIdentityCompleteTable(connection);
        //CreateMultiKeyTable();
    }

    private static void CreateCompleteTable(DbConnection connection)
    {
        if (connection.SchemaObjectExists<CompleteTable>())
            return;

        connection.ExecuteNonQuery(@"
            CREATE TABLE ""CompleteTable"" (
                ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                ""ColumnBigInt"" NUMBER(19),
                ""ColumnBinary"" RAW(2000),
                ""ColumnBit"" NUMBER(1),
                ""ColumnChar"" CHAR(1),
                ""ColumnDate"" DATE,
                ""ColumnDateTime"" TIMESTAMP,
                ""ColumnDateTime2"" TIMESTAMP(7),
                ""ColumnDateTimeOffset"" TIMESTAMP(7) WITH TIME ZONE,
                ""ColumnDecimal"" NUMBER(18,2),
                ""ColumnFloat"" BINARY_DOUBLE,
                ""ColumnImage"" BLOB,
                ""ColumnInt"" NUMBER(10),
                ""ColumnMoney"" NUMBER(19,4),
                ""ColumnNChar"" NCHAR(1),
                ""ColumnNText"" NCLOB,
                ""ColumnNumeric"" NUMBER(18,2),
                ""ColumnNVarChar"" NVARCHAR2(2000),
                ""ColumnReal"" BINARY_FLOAT,
                ""ColumnSmallDateTime"" TIMESTAMP(0),
                ""ColumnSmallInt"" NUMBER(5),
                ""ColumnSmallMoney"" NUMBER(10,4),
                ""ColumnText"" CLOB,
                ""ColumnTime"" INTERVAL DAY(0) TO SECOND(7),
                ""ColumnTimestamp"" TIMESTAMP,
                ""ColumnTinyInt"" NUMBER(3),
                ""ColumnUniqueIdentifier"" RAW(16),
                ""ColumnVarBinary"" BLOB,
                ""ColumnVarChar"" VARCHAR2(2000),
                ""ColumnXml"" XMLTYPE
            )");
    }

    private static void CreateNonIdentityCompleteTable(DbConnection connection)
    {
        if (connection.SchemaObjectExists<NonIdentityCompleteTable>())
            return;

        connection.ExecuteNonQuery(@"
            CREATE TABLE ""NonIdentityCompleteTable"" (
                ""Id"" NUMBER(19) PRIMARY KEY NOT NULL,
                ""ColumnBigInt"" NUMBER(19),
                ""ColumnBinary"" RAW(2000),
                ""ColumnBit"" NUMBER(1),
                ""ColumnChar"" CHAR(1),
                ""ColumnDate"" DATE,
                ""ColumnDateTime"" TIMESTAMP,
                ""ColumnDateTime2"" TIMESTAMP(7),
                ""ColumnDateTimeOffset"" TIMESTAMP(7) WITH TIME ZONE,
                ""ColumnDecimal"" NUMBER(18,2),
                ""ColumnFloat"" BINARY_DOUBLE,
                ""ColumnImage"" BLOB,
                ""ColumnInt"" NUMBER(10),
                ""ColumnMoney"" NUMBER(19,4),
                ""ColumnNChar"" NCHAR(1),
                ""ColumnNText"" NCLOB,
                ""ColumnNumeric"" NUMBER(18,2),
                ""ColumnNVarChar"" NVARCHAR2(2000),
                ""ColumnReal"" BINARY_FLOAT,
                ""ColumnSmallDateTime"" TIMESTAMP(0),
                ""ColumnSmallInt"" NUMBER(5),
                ""ColumnSmallMoney"" NUMBER(10,4),
                ""ColumnText"" CLOB,
                ""ColumnTime"" INTERVAL DAY(0) TO SECOND(7),
                ""ColumnTimestamp"" TIMESTAMP,
                ""ColumnTinyInt"" NUMBER(3),
                ""ColumnUniqueIdentifier"" RAW(16),
                ""ColumnVarBinary"" BLOB,
                ""ColumnVarChar"" VARCHAR2(2000),
                ""ColumnXml"" XMLTYPE
            )");
    }

    private static void CreateMultiKeyTable()
    {
        var commandText = @"IF (NOT EXISTS(SELECT 1 FROM [sys].[objects] WHERE type = 'U' AND name = 'MultiKeyTable'))
                BEGIN
                    CREATE TABLE [dbo].[MultiKeyTable]
                    (
                        [Pk1] INT NOT NULL,
                        [Pk2] VARCHAR(16) NOT NULL,
                        [ColumnVarChar] VARCHAR(MAX) NULL,
                        CONSTRAINT [PK_MultiKeyTable] PRIMARY KEY
                        (
                            [Pk1] ASC,
                            [Pk2] ASC
                        )
                    ) ON [PRIMARY];
                END";
        using var connection = new OracleConnection(ConnectionString).EnsureOpen();
        connection.ExecuteNonQuery(commandText);
    }

    #endregion

    #region CompleteTable

    public static IEnumerable<CompleteTable> CreateCompleteTables(int count, IEnumerable<Field>? fields = null)
    {
        using var connection = new OracleConnection(ConnectionString);
        List<CompleteTable> tables = Helper.CreateCompleteTables(count);
        connection.InsertAll(tables, fields: fields);
        return tables;
    }

    #endregion

    #region NonIdentityCompleteTable

    public static IEnumerable<NonIdentityCompleteTable> CreateNonIdentityCompleteTables(int count, IEnumerable<Field>? fields = null)
    {
        using (var connection = new OracleConnection(ConnectionString))
        {
            var tables = Helper.CreateNonIdentityCompleteTables(count);
            connection.InsertAll(tables, fields: fields);
            return tables;
        }
    }

    #endregion

    //#region MultiKeyTable
    //public static IEnumerable<MultiKeyTable> CreateMultiKeyTables(int count)
    //{
    //    using (var connection = new OracleConnection(ConnectionString))
    //    {
    //        var tables = Helper.CreateMultiKeyTables(count);
    //        connection.InsertAll(tables);
    //        return tables;
    //    }
    //}
    //#endregion
}
